#!/usr/bin/env bash
# This bash script groups visitors by IP and HTTP status code, and displays,
# the data.
# Format: OCCURENCE_NUMBER IP HTTP_CODE

awk '{ print $1, $9 }' apache-access.log | sort | uniq -c | sort -nr
